# Diese Config wird noch nicht aktiv genutzt!
JoinMessage: '&7-> &d{Player}&7 hat den Server &abetreten&7.'
LeaveMessage: '&7<- &d{Player}&7 hat den Server &cverlassen&7.'
#
ProtectSkeletonFromFire: true
#
ProtectedBlocks:
- 'OBSIDIAN'
#
ExplosionDamageMultiplier: 0.5
#
NoMovingBlocks:
- 'SPAWNER'
#
RandomArrow:
    MaxRandom: 25
    Intergers:
        Fire: default
        TNT: 5
        Lightning: 15
        Explosion: 25
# 
SupportedBlocks:
- 'FENCES'
- 'IRON_BARS'
- 'GLASS_PANE'
- 'ALL SOLID BLOCKS'
- 'WALLS'
#
UnSupportetBlocks: 
- 'LEAVES'
- 'FENCE_GATES'
- 'TRAPDOORS'
- 'CHAIN'