name: AdvancedHardcore
version: 0.91
author: Jonosa
main: main.Main
api-version: 1.16

commands:
  replacebiome:
    description: Ersetzt ein Biom
  biomeliste:
    description: Liste aller Biome (1.6.4)
  fly:
    description: Fliegen umschalten
  speed:
    description: Setzt Flug und Geh Geschwindigkeit
  getitem:
    description: Gibt dir wichtige Tools
  heal:
    description: Heil einen Spieler
  tglmethod:
    description: Toggle Method
  blockdata:
    description: Zeigt dir die Blockdata des angeklickten Blocks
# Zweimal pro Klick bei PlayerInteractEvent
# Equipment von Mobs testen
# Fallende Blöcke immer platzieren
# Playerdeath 4
# Items die despawnen ergreifbar machen
# item.getPersistentDataContainer()